### ISSUE TITLE
Shared CSS Properties

### ISSUE THREAD

**Issue by cyouh95** [DeeterCesler/prj-rev-bwfs-dasmoto#1]
Instead of having to list `font-weight: bold;` 3 times in your CSS file, you could alternatively specify shared properties for multiple selectors by using commas:

```css
.header, h2, strong {
  font-weight: bold;
}
```

https://github.com/DeeterCesler/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/style.css
